development: &default
  adapter: postgresql
  database: wiggle_audit_tool_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: wiggle_audit_tool_test
